### ISSUE TITLE
Error executing command: unable to generate website: unexpected error: openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by dineshhg** [hashicorp/terraform-plugin-docs#217]
### 0.4.0 Release is not working anymore
Error executing command: unable to generate website: unexpected error: openpgp: signature made by unknown entity

![tempsnip](https://user-images.githubusercontent.com/91111785/216645260-831f95db-8af5-4d07-b6a6-b3e8f29f9a1e.png)

## I'm not able to find any resource saying that the `0.4.0` version will stop working going forward.

---- 

# Solution: Upgrade to the latest 0.13.0

**Comment by bflad** [comment]
Hi @dineshhg 👋 Thank you for reporting this and sorry you ran into trouble here.

What I suspect happened here was part of https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570, where new Terraform patch releases were created due to a security concern. The `terraform-plugin-docs generate` command relies on calling Terraform CLI to get the documentation out of the provider except when the recent `-provider-schema` flag is used. If the `terraform-plugin-docs` project was to introduce any breaking changes, they would be announced in the changelog and release notes, but in this case it was a Terraform CLI issue so there was no announcement. I think the best thing in this case was to do exactly what you did, raise a GitHub bug report here.

Since there is nothing actionable here, except potentially making the error messaging clear about the issue being with Terraform CLI (already covered by https://github.com/hashicorp/terraform-plugin-docs/issues/136), I'm going to close this issue. We do really appreciate the report and solution though -- it likely helped others.
