### ISSUE TITLE
Unable to render schema without a 'required' attribute.

### ISSUE THREAD

**Issue by MeanMangosteen** [hashicorp/terraform-plugin-docs#29]
I'm trying to generate docs for a custom provider, however the tool produces an error when it tries to render the [following schema](https://github.com/GorillaStack/terraform-provider-gorillastack/blob/cbb847a64127a81238f847f8151ff63cecbb7dc5/gorillastack/schema_trigger.go#L210):
```
func manualTriggerSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"trigger": {
			Type:     schema.TypeString,
			Computed: true,
		},
	}
}
```
Which produces the following error:
```
Error executing command: unable to generate website: unable to render doc "gorillastack_rule": unable to render template for "gorillastack_rule": unable to render schema: unable to render schema: no match for "manual"
```

Adding a dummy 'required' attribute fixes this issue:

```
func manualTriggerSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"trigger": {
			Type:     schema.TypeString,
			Computed: true,
		},
		"dummy": {
			Type:     schema.TypeString,
			Required: true,
		},
	}
}
```

Is it a requirement that a 'Required' attribute must be present in a schema or is this a bug within the tool?

Thanks.

**Comment by paultyng** [comment]
Its definitely not intended that you must have at least one required attribute. Its hard to say what the bug is though without seeing the full resource schema. You can see the data that Terraform is sending to the tool by running `terraform providers schema -json` on a configuration with your provider.

I'll test that repo locally though and see if I can track it down.

**Comment by paultyng** [comment]
Figured out the issue here, the problem is that you have `MinItems: 1` and `Optional: true` on the `manual` block itself. They are incompatible (`Required: true` is actually shorthand for `MinItems: 1` on blocks).

I'm not sure if this is allowed by the old SDK (you should update to the [external SDK if possibe](https://github.com/hashicorp/terraform-plugin-sdk), there are some upgrade tools for it) or if its just a general potential issue, so I'll need to dig in a bit more.

**Comment by paultyng** [comment]
Actually I was mistaken. The issue here is that all of the child schema (`trigger` is computed, but this block is not marked `Computed: true` but probably should be since its not something a user can set.

**Comment by paultyng** [comment]
I added a better error message in c58c3d7daa543742ca0bd8857ba8d6b08d8cc225
