### ISSUE TITLE
Duplicate docs are generated when template names have `<provider-name>_` prefix

### ISSUE THREAD

**Issue by ctreatma** [hashicorp/terraform-plugin-docs#347]
### Terraform CLI and terraform-plugin-docs Versions

```
$ terraform version
Terraform v1.5.7
on darwin_arm64

$ tfplugindocs --version
tfplugindocs Version 0.18.0 from commit 4c08c0eed13b3819b4342dc0cb119b3be62305b1
```

### Provider Code

```go
I'm attempting to run `tfplugindocs --migrate` followed by `tfplugindocs --generate` to convert existing provider docs from hand-written to generated: https://github.com/equinix/terraform-provider-equinix
```

### Expected Behavior

The generator creates one Markdown page per resource or data source

### Actual Behavior

The generator creates two Markdown pages per resource or data source: one page has the provider name prefix in the file name and the other does not

### Steps to Reproduce

1. Create templates that match the [documented conventional paths](https://github.com/hashicorp/terraform-plugin-docs/?tab=readme-ov-file#conventional-paths) (for example, according to that, a template for `caller_identity` in the `aws` provider would be named `aws_caller_identity.md.tmpl`)
2. Run `tfplugindocs --generate`

I'm using `tfplugindocs --migrate` to create templates from existing docs; it produces the expected templates that have the conventional path with the provider name prefix.

The generator produces files that match the template names and have the expected contents, but it _also_ produces files without the provider name prefix that use a default template.

Note:  I confirmed that if I remove the provider prefix from the template files I only get the files without the provider name prefix, but I want to get one set of generated files that has the conventional path with the provider name prefix.

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @ctreatma 👋 Thank you for reporting this and sorry you ran into trouble here. I can reproduce this behavior via:

```shell
gh repo clone equinix/terraform-provider-equinix
cd terraform-provider-equinix
tfplugindocs migrate
go generate ./...
git status
```

I'm guessing there are at least two mutually exclusive options here:

* Having the `migrate` subcommand detect the provider name prefixed files and move them automatically to the "expected" location
* Having the `generate` subcommand detect the provider name prefixed files and treat them as equivalent to the "expected" location by overwriting the existing files instead of creating new files

Adjusting the `migrate` subcommand feels slightly more appropriate in this situation since the Terraform Registry does not particularly care the exact filenames when ingressing the documentation (only the file extensions) and since the _intention_ of that command is to prepare the codebase for the `generate` subcommand.
